"""Initial revision

Revision ID: b9e028ea9f2f
Revises: 
Create Date: 2025-12-25 03:47:21.194697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e028ea9f2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('university_card', sa.String(length=100), nullable=False),
    sa.Column('study_group', sa.String(length=100), nullable=False),
    sa.Column('redmine_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
